project:
  type: website
  output-dir: 'docs'

website:
  title: "Campaigns"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - festivus-games.qmd

format:
  html:
    theme:
      light: cerulean
      dark: cyborg
    css: styles.css
    toc: true



